module

import Lean
import Lake.CLI.Main
import Lake.Load.Workspace

/-!
# ExtractDeps — Generic trusted-base extraction

Given a declaration name and a module prefix, recursively extracts the project
declarations that the *statement* of the target depends on.

## Semantics

The traversal follows "trusted formalization base" semantics:

- **defs/opaques**: descend into type *and* value (the value *is* the definition)
- **theorems**: type only (the proof is kernel-checked)
- **inductives**: type and constructor types
- **ctors/recs**: type only

This answers: "what project declarations must a reader trust to accept this
formal statement as meaningful?"

## Filtering

Auto-generated declarations are dropped by default (pass `--all` to keep them):
- `._proof_N`, `._uniq_N`, `match_N`, `eq_N` (internal name components)
- Recursors, `noConfusion`, `casesOn`, `brecOn`, etc.
- Constructors (`.mk`) and recursor/quotient infos

Structure field projections (`.Z`, `.P`, `.slicing`, etc.) are kept — they
carry mathematical meaning.

The remaining declarations are grouped by source module.

## Usage

```
lake exe extractDeps <declName> [modulePrefix]
```

`modulePrefix` defaults to the first component of `declName`. Pass `--all` to
include auto-generated declarations.
-/

open Lake Lean

/-- Whether a name component looks internal/auxiliary. -/
private def isAuxComponent (s : String) : Bool :=
  s.startsWith "_" || s.startsWith "match_" || s.startsWith "proof_" || s.startsWith "eq_"

/-- Whether a name is internal/auxiliary. -/
private def isInternalName (n : Name) : Bool :=
  n.isInternal || n.isImplementationDetail || go n
where
  go : Name → Bool
    | .anonymous => false
    | .num p _ => go p
    | .str p s =>
      isAuxComponent s
      || s ∈ ["brecOn", "below", "casesOn", "noConfusion", "noConfusionType",
              "recOn", "rec", "ind", "mk", "sizeOf_spec", "inject", "injEq",
              "ctorIdx", "ext_iff"]
      || go p

/-- Whether a declaration is auto-generated (projection, aux recursor, noConfusion). -/
private def isAutoGenerated (env : Environment) (n : Name) : Bool :=
  env.isProjectionFn n || isAuxRecursor env n || isNoConfusion env n

/-- Whether a name starts with the given prefix. -/
private def hasPrefix (n : Name) (prefix_ : Name) : Bool :=
  n == prefix_ || match n with
    | .str p _ => hasPrefix p prefix_
    | .num p _ => hasPrefix p prefix_
    | .anonymous => false

namespace ExtractDeps

structure Config where
  /-- Only report declarations whose source module starts with this prefix. -/
  modulePrefix : Name
  /-- If true, include auto-generated declarations. -/
  includeAutoGenerated : Bool := false

structure State where
  visited : NameSet := {}
  /-- Declarations reachable from the target's *type*. -/
  typeDeps : NameSet := {}
  /-- Declarations reachable from the target's *value* but not its type. -/
  valueDeps : NameSet := {}

abbrev M := ReaderT (Environment × Config) (StateM State)

private def getEnv : M Environment := return (← read).1
private def getConfig : M Config := return (← read).2

/-- Check if a declaration's source module matches the prefix. -/
private def isInProjectModule (c : Name) : M Bool := do
  let env ← getEnv
  let cfg ← getConfig
  match env.getModuleIdxFor? c with
  | some modIdx =>
    let modName := env.header.moduleNames[modIdx.toNat]!
    return hasPrefix modName cfg.modulePrefix
  | none => return false

/-- Should this declaration be reported? -/
private def shouldReport (c : Name) : M Bool := do
  let env ← getEnv
  unless ← isInProjectModule c do return false
  if !(← getConfig).includeAutoGenerated then
    if isInternalName c then return false
    -- Drop recursors, constructors, quotient info, noConfusion, aux recursors.
    -- Keep structure projections — they carry mathematical meaning
    -- (e.g., `.Z` is the central charge, `.P` is the slicing).
    if isAuxRecursor env c || isNoConfusion env c then return false
    match env.find? c with
    | some (.ctorInfo _) | some (.recInfo _) | some (.quotInfo _) => return false
    | _ => pure ()
  return true

/-- Collect constants from an expression. -/
private def collectExpr (e : Expr) (collect : Name → M Unit) : M Unit :=
  e.getUsedConstants.forM collect

/--
Recursively collect project declarations reachable from constant `c`.

For the trusted base: descend into def/opaque/inductive bodies (they define
meaning), but only into theorem *types* (proofs are kernel-checked).
-/
partial def collect (c : Name) : M Unit := do
  let s ← get
  if s.visited.contains c then return
  modify fun s => { s with visited := s.visited.insert c }
  let env ← getEnv
  match env.find? c with
  | some (.defnInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
    collectExpr v.value collect
  | some (.thmInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    -- Type only — proof is kernel-checked
    collectExpr v.type collect
  | some (.opaqueInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
    collectExpr v.value collect
  | some (.inductInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
    v.ctors.forM collect
  | some (.ctorInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
  | some (.recInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
  | some (.axiomInfo v) =>
    if ← shouldReport c then
      modify fun s => { s with typeDeps := s.typeDeps.insert c }
    collectExpr v.type collect
  | some (.quotInfo _) => pure ()
  | none => pure ()

/--
Top-level extraction. Collects from the target's type, then separately from
its value, partitioning into type-deps and value-only-deps.
-/
def extract (env : Environment) (cfg : Config) (target : Name) :
    NameSet × NameSet := Id.run do
  -- Phase 1: collect from type
  let some info := env.find? target | return ({}, {})
  let mut s : State := {}
  (_, s) := ((do
    collectExpr info.type collect
  : M Unit).run (env, cfg)).run s
  let typeDeps := s.typeDeps

  -- Phase 2: collect from value (for non-theorems)
  match info with
  | .defnInfo v =>
    (_, s) := ((collectExpr v.value collect : M Unit).run (env, cfg)).run s
  | .opaqueInfo v =>
    (_, s) := ((collectExpr v.value collect : M Unit).run (env, cfg)).run s
  | .inductInfo v =>
    (_, s) := ((v.ctors.forM collect : M Unit).run (env, cfg)).run s
  | _ => pure ()
  let allDeps := s.typeDeps
  let valueDeps := allDeps.diff typeDeps

  return (typeDeps, valueDeps)

end ExtractDeps

/-- Extract the root (first) component of a hierarchical name. -/
private def rootPrefix : Name → Name
  | .str .anonymous s => .str .anonymous s
  | .str p _ => rootPrefix p
  | .num p _ => rootPrefix p
  | .anonymous => .anonymous

public unsafe def main (args : List String) : IO UInt32 := do
  let (flags, positional) := args.partition (·.startsWith "--")
  let includeAuto := flags.contains "--all"

  unless positional.length ≥ 1 do
    IO.eprintln "Usage: lake exe extractDeps <declName> [modulePrefix] [--all]"
    IO.eprintln ""
    IO.eprintln "  Extracts project declarations reachable from the statement of <declName>."
    IO.eprintln "  [modulePrefix] filters to declarations under that prefix (default: first"
    IO.eprintln "  component of declName)."
    IO.eprintln "  --all  Include auto-generated declarations (._proof_N, projections, etc.)"
    return 1

  let targetStr := positional[0]!
  let target := targetStr.toName

  let prefixName := if positional.length ≥ 2 then
    positional[1]!.toName
  else
    match target with
    | .str p _ => match p with
      | .anonymous => target
      | _ => rootPrefix p
    | _ => target

  let cfg : ExtractDeps.Config := {
    modulePrefix := prefixName
    includeAutoGenerated := includeAuto
  }

  -- Load workspace and environment
  let (elanInstall?, leanInstall?, lakeInstall?) ← Lake.findInstall?
  let loadConfig ← Lake.MonadError.runEIO <|
    Lake.mkLoadConfig { elanInstall?, leanInstall?, lakeInstall? }
  let some ws ← Lake.loadWorkspace loadConfig |>.toBaseIO
    | do IO.eprintln "Failed to load Lake workspace"; return 1

  -- Import project libraries, skipping spec/blueprint modules that have
  -- meta-only dependencies not available at runtime.
  -- TODO: make this configurable via CLI flags
  let skipLibs : Array Name := #[`BridgelandSpec, `BridgelandBlueprint]
  let imports := ws.root.leanLibs
    |>.filter (fun lib => !skipLibs.contains lib.name)
    |>.flatMap (fun lib => lib.config.roots.map fun module => { module })
  enableInitializersExecution
  let env ← Lean.importModules imports {}

  unless env.contains target do
    IO.eprintln s!"Declaration not found: {target}"
    return 1

  let (typeDeps, valueDeps) := ExtractDeps.extract env cfg target

  -- Group by module
  let mut moduleMap : Std.HashMap Name (Array Name) := {}
  for n in typeDeps.toArray.qsort Name.lt do
    if let some modIdx := env.getModuleIdxFor? n then
      let modName := env.header.moduleNames[modIdx.toNat]!
      moduleMap := moduleMap.insert modName
        ((moduleMap.getD modName #[]).push n)

  -- Print results
  IO.println s!"# Trusted base for `{target}`"
  IO.println s!""
  IO.println s!"Prefix filter: `{prefixName}`"
  IO.println s!"Auto-generated: {if includeAuto then "included" else "excluded"}"
  IO.println s!""
  IO.println s!"## Type dependencies ({typeDeps.size} declarations)"
  IO.println s!""

  let modules := moduleMap.toArray.qsort (fun a b => a.1.lt b.1)
  for (modName, decls) in modules do
    IO.println s!"### {modName} ({decls.size})"
    for d in decls do
      IO.println s!"- `{d}`"
    IO.println ""

  if valueDeps.size > 0 then
    IO.println s!"## Value-only dependencies ({valueDeps.size} declarations)"
    IO.println s!""
    let mut valModuleMap : Std.HashMap Name (Array Name) := {}
    for n in valueDeps.toArray.qsort Name.lt do
      if let some modIdx := env.getModuleIdxFor? n then
        let modName := env.header.moduleNames[modIdx.toNat]!
        valModuleMap := valModuleMap.insert modName
          ((valModuleMap.getD modName #[]).push n)
    let valModules := valModuleMap.toArray.qsort (fun a b => a.1.lt b.1)
    for (modName, decls) in valModules do
      IO.println s!"### {modName} ({decls.size})"
      for d in decls do
        IO.println s!"- `{d}`"
      IO.println ""

  return 0
