name = "BridgelandStability"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BridgelandStability"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[require]]
name = "LeanArchitect"
git = "https://github.com/mattrobball/LeanArchitect"
rev = "e8c18617df9210f176e6fada714ab1e907e2cf93"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls"
rev = "master"

[[lean_lib]]
name = "BridgelandStability"
srcDir = "."

[[lean_lib]]
name = "BridgelandSpec"
srcDir = "."

[[lean_lib]]
name = "BridgelandBlueprint"
srcDir = "."
