name = "BridgelandStability"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BridgelandStability"]

[leanOptions]
autoImplicit = false

[[require]]
name = "LeanArchitect"
git = "https://github.com/mattrobball/LeanArchitect"
rev = "extract-all-module"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls"
rev = "master"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "BridgelandStability"
srcDir = "."

[[lean_lib]]
name = "BridgelandSpec"
srcDir = "."

[[lean_lib]]
name = "BridgelandBlueprint"
srcDir = "."

[[lean_exe]]
name = "checkdecls"
root = "Checkdecls"
supportInterpreter = true
