import BridgelandStability.Deformation.TStructure
import VersoManual

open Verso.Genre Manual

set_option verso.docstring.allowMissing true

#doc (Manual) "Deformation: TStructure" =>
%%%
htmlSplit := .never
%%%

# deformedGtGen

Generators of $`Q(> t)`: $`Q`-semistable objects with some phase $`\psi > t` (Bridgeland Node 7.8a).

Construction: Defined as $`E \mapsto \exists \psi,\, t < \psi \wedge \operatorname{deformedPred}(\psi, E)`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtGen}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedGtGen&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtGen%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedGtPred

$`Q(> t)`: the extension-closed subcategory generated by the $`Q(\psi)` with $`\psi > t` (Bridgeland p.6, Node 7.8a).

Construction: The extension closure of `deformedGtGen`: the smallest extension-closed subcategory containing all $`Q`-semistable objects of phase $`> t`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedGtPred&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedGtPred\_anti

Anti-monotonicity of $`Q(> t)`: if $`t_1 \le t_2` then $`Q(> t_2) \subseteq Q(> t_1)`.

Proof: If $`t_2 < \psi` and $`t_1 \le t_2`, then $`t_1 < \psi`. Apply `ExtensionClosure.mono`.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_anti}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedGtPred_anti&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedGtPred_anti%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLeGen

Generators of $`Q(\le t)`: $`Q`-semistable objects with some phase $`\psi \le t` (Bridgeland Node 7.8a).

Construction: Defined as $`E \mapsto \exists \psi,\, \psi \le t \wedge \operatorname{deformedPred}(\psi, E)`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLeGen}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLeGen&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLeGen%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLePred

$`Q(\le t)`: the extension-closed subcategory generated by the $`Q(\psi)` with $`\psi \le t` (Bridgeland p.6, Node 7.8a).

Construction: The extension closure of `deformedLeGen`: the smallest extension-closed subcategory containing all $`Q`-semistable objects of phase $`\le t`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLePred&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLePred\_mono

Monotonicity of $`Q(\le t)`: if $`t_1 \le t_2` then $`Q(\le t_1) \subseteq Q(\le t_2)`.

Proof: If $`\psi \le t_1 \le t_2`, then $`\psi \le t_2`. Apply `ExtensionClosure.mono`.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_mono}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLePred_mono&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_mono%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLePred\_of\_deformedLtPred

Any $`Q(< t)`-object is in $`Q(\le t)`: $`\psi < t` implies $`\psi \le t`.

Proof: Immediate from `ExtensionClosure.mono` applied to the weakening $`\psi < t \implies \psi \le t`.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_of_deformedLtPred}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLePred_of_deformedLtPred&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLePred_of_deformedLtPred%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLtGen

Generators of $`Q(< t)`: $`Q`-semistable objects with some phase $`\psi < t` (Bridgeland Node 7.8a / 7.9).

Construction: Defined as $`E \mapsto \exists \psi,\, \psi < t \wedge \operatorname{deformedPred}(\psi, E)`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtGen}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLtGen&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtGen%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLtPred

$`Q(< t)`: the extension-closed subcategory generated by the $`Q(\psi)` with $`\psi < t` (Bridgeland p.6, Node 7.8a / 7.9).

Construction: The extension closure of `deformedLtGen`: the smallest extension-closed subcategory containing all $`Q`-semistable objects of phase $`< t`.


{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLtPred&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# deformedLtPred\_mono

Monotonicity of $`Q(< t)`: if $`t_1 \le t_2` then $`Q(< t_1) \subseteq Q(< t_2)`.

Proof: If $`\psi < t_1 \le t_2`, then $`\psi < t_2`. Apply `ExtensionClosure.mono`.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_mono}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20deformedLtPred_mono&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.deformedLtPred_mono%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero\_of\_deformedGt\_deformedLe

Orthogonality of $`Q(> t)` and $`Q(\le t)` (Node 7.8b). Every morphism from a $`Q(> t)`-object to a $`Q(\le t)`-object is zero.

Proof: By `ExtensionClosure.hom_eq_zero`: it suffices to check generators. For generators $`A \in Q(\psi_1)` with $`\psi_1 > t` and $`B \in Q(\psi_2)` with $`\psi_2 \le t`, the phase gap $`\psi_2 < \psi_1` gives $`\operatorname{Hom}(A, B) = 0` by `hom_eq_zero_of_deformedPred`.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedGt_deformedLe}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero_of_deformedGt_deformedLe&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedGt_deformedLe%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero\_of\_deformedGt\_deformedLt

Orthogonality of $`Q(> t)` and $`Q(< t)`: every morphism from a $`Q(> t)`-object to a $`Q(< t)`-object is zero.

Proof: Same as `hom_eq_zero_of_deformedGt_deformedLe` but with strict inequality on both sides.

{docstring CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedGt_deformedLt}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero_of_deformedGt_deformedLt&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.WithClassMap.hom_eq_zero_of_deformedGt_deformedLt%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# chain\_hom\_eq\_zero\_gap\_deformed

Any morphism from the $`k`-th chain object of a $`Q`-HN filtration $`F_X` to an object $`Y` admitting a filtration $`F_Y` is zero, provided every phase of $`F_X` is strictly greater than every phase of $`F_Y`. This is the `deformedPred` analogue of `chain_hom_eq_zero_gap`.

Proof: Induction on $`k`. Base: $`E_0 = 0`. Inductive step: the Yoneda exact sequence factors the map through the $`k`-th semistable factor of $`F_X`, and `hom_eq_zero_of_gt_phases_deformed` shows this factor maps to zero into $`Y`.

{docstring CategoryTheory.Triangulated.chain_hom_eq_zero_gap_deformed}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20chain_hom_eq_zero_gap_deformed&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.chain_hom_eq_zero_gap_deformed%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# chain\_hom\_eq\_zero\_of\_gt\_deformed

Any morphism from a $`Q(\psi)`-semistable object $`A` to the $`k`-th chain object of a $`Q`-HN filtration whose phases are all strictly less than $`\psi` is zero. This is the `deformedPred` analogue of `chain_hom_eq_zero_of_gt`.

Proof: Induction on $`k`. Base: $`k = 0` is trivial since $`E_0 = 0`. Inductive step: the coYoneda exact sequence on the $`k`-th distinguished triangle gives that any map $`A \to E_{k+1}` factors through $`A \to F_k` (the $`k`-th factor), but `hom_eq_zero_of_deformedPred` kills this by the phase gap.

{docstring CategoryTheory.Triangulated.chain_hom_eq_zero_of_gt_deformed}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20chain_hom_eq_zero_of_gt_deformed&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.chain_hom_eq_zero_of_gt_deformed%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_deformedGt\_deformedLe\_triangle\_of\_enveloped\_interval

For any nonzero interval object $`E` in a thin finite-length interval with the $`W`-phase envelope condition, there exists a distinguished triangle $`X \to E \to Y \to X[1]` with $`X \in Q(> t)` and $`Y \in Q(\le t)`.

Proof: First construct the $`Q`-HN filtration via `exists_deformedHN_of_enveloped_interval`, then apply `exists_deformedGt_deformedLe_triangle_of_hn` at cutoff $`t`.

{docstring CategoryTheory.Triangulated.exists_deformedGt_deformedLe_triangle_of_enveloped_interval}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_deformedGt_deformedLe_triangle_of_enveloped_interval&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.exists_deformedGt_deformedLe_triangle_of_enveloped_interval%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_deformedGt\_deformedLe\_triangle\_of\_hn

A $`Q`-HN filtration split at cutoff $`t` gives a distinguished triangle whose two pieces lie in $`Q(> t)` and $`Q(\le t)`.

Proof: Apply `split_hn_filtration_at_cutoff` to the $`Q`-HN filtration. The factors with phase $`> t` generate $`Q(> t)` via extension closure, and those with phase $`\le t` generate $`Q(\le t)`.

{docstring CategoryTheory.Triangulated.exists_deformedGt_deformedLe_triangle_of_hn}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_deformedGt_deformedLe_triangle_of_hn&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.exists_deformedGt_deformedLe_triangle_of_hn%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_deformedGt\_deformedLt\_triangle\_of\_hn

A $`Q`-HN filtration split at cutoff $`t` gives a distinguished triangle whose two pieces lie in $`Q(> t)` and $`Q(< t)`, when no factor has phase exactly $`t`.

Proof: Same as `exists_deformedGt_deformedLe_triangle_of_hn` but with strict inequality: the $`\le t` piece has all phases $`< t` when $`t` is not a phase of any factor.

{docstring CategoryTheory.Triangulated.exists_deformedGt_deformedLt_triangle_of_hn}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_deformedGt_deformedLt_triangle_of_hn&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.exists_deformedGt_deformedLt_triangle_of_hn%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_deformedHN\_of\_enveloped\_interval

Lemma 7.7 for the deformed slicing: if a thin interval carries strict finite length and every nonzero object has $`W`-phase at least $`\varepsilon_0` away from the boundaries, then every nonzero interval object admits a $`Q`-HN filtration with phases in $`(a + \varepsilon_0, b - \varepsilon_0)`.

Proof: Apply `hn_exists_in_thin_interval` with $`L = a + \varepsilon_0`, $`U = b - \varepsilon_0`, Hom vanishing from `hom_eq_zero_of_enveloped_interval_semistable`, and destabilizing bound from the window hypothesis. Retype the $`\operatorname{ssf}`-semistable factors as `deformedPred` using the interval $`(a, b)` as witness.

{docstring CategoryTheory.Triangulated.exists_deformedHN_of_enveloped_interval}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_deformedHN_of_enveloped_interval&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.exists_deformedHN_of_enveloped_interval%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero\_of\_enveloped\_interval\_semistable

Hom vanishing for two interval-semistable objects whose $`W`-phases sit $`\varepsilon_0` away from the interval boundaries: convert both to `deformedPred` using the same interval as witness, then apply `hom_eq_zero_of_deformedPred`.

Proof: Both objects are $`\operatorname{ssf}`-semistable with phases in $`(a + \varepsilon_0, b - \varepsilon_0)`, so each is a `deformedPred` object witnessed by $`(a, b)`. Apply Lemma 7.6.

{docstring CategoryTheory.Triangulated.hom_eq_zero_of_enveloped_interval_semistable}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero_of_enveloped_interval_semistable&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.hom_eq_zero_of_enveloped_interval_semistable%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero\_of\_gt\_phases\_deformed

A morphism from a $`Q(\psi)`-semistable object to an HN-filtered object whose phases are all strictly less than $`\psi` is zero.

Proof: Apply `chain_hom_eq_zero_of_gt_deformed` at the top of the chain, using the isomorphism $`E_n \cong E`.

{docstring CategoryTheory.Triangulated.hom_eq_zero_of_gt_phases_deformed}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero_of_gt_phases_deformed&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.hom_eq_zero_of_gt_phases_deformed%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero\_of\_phase\_gap\_deformed

Morphisms between $`Q`-HN filtered objects with a phase gap are zero: if every phase of $`F_X` is strictly greater than every phase of $`F_Y`, then $`\operatorname{Hom}(X, Y) = 0`.

Proof: Apply `chain_hom_eq_zero_gap_deformed` at the top of the chain for $`F_X`, using $`X_n \cong X`.

{docstring CategoryTheory.Triangulated.hom_eq_zero_of_phase_gap_deformed}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero_of_phase_gap_deformed&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.hom_eq_zero_of_phase_gap_deformed%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.Deformation.TStructure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)
