/-
Copyright (c) 2026 Mathlib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formalization
-/
module

public import BridgelandStability.PostnikovTower.Defs
public import Mathlib.CategoryTheory.Triangulated.Triangulated

/-!
# Extension Closure

The extension-closed subcategory generated by an object property.
-/

@[expose] public section

set_option backward.privateInPublic true
set_option backward.privateInPublic.warn false
set_option backward.proofsInPublic true

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open scoped ZeroObject

universe v u

/-! ### Extension closure (Bridgeland p.6) -/

/-- The extension-closed subcategory generated by an object property `P` (Bridgeland p.6).
An object `E` is in `P.ExtensionClosure` if it is zero, satisfies `P`, or is the middle
term of a distinguished triangle whose other two terms are in `P.ExtensionClosure`. -/
inductive CategoryTheory.ObjectProperty.ExtensionClosure {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    (P : ObjectProperty C) : ObjectProperty C where
  | zero {E : C} : IsZero E → P.ExtensionClosure E
  | mem {E : C} : P E → P.ExtensionClosure E
  | ext {X E Y : C} {f : X ⟶ E} {g : E ⟶ Y} {h : Y ⟶ X⟦(1 : ℤ)⟧} :
      Triangle.mk f g h ∈ distTriang C →
      P.ExtensionClosure X →
      P.ExtensionClosure Y →
      P.ExtensionClosure E

namespace CategoryTheory.ObjectProperty.ExtensionClosure

/-- Extension closure is monotone: if `P ≤ Q` then `P.ExtensionClosure ≤ Q.ExtensionClosure`. -/
theorem mono {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P Q : ObjectProperty C} (h : P ≤ Q) :
    P.ExtensionClosure ≤ Q.ExtensionClosure := by
  intro E hE
  induction hE with
  | zero hZ => exact .zero hZ
  | mem hP => exact .mem (h _ hP)
  | ext hT _ _ ihX ihY => exact .ext hT ihX ihY

/-- If generators are orthogonal (`Hom(P, Q) = 0`), their extension closures are orthogonal.
Proof by nested induction on the `ExtensionClosure` structure, using the exact Hom sequences
from distinguished triangles. -/
theorem hom_eq_zero {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P Q : ObjectProperty C}
    (h : ∀ (E F : C), P E → Q F → ∀ (f : E ⟶ F), f = 0)
    {E F : C} (hE : P.ExtensionClosure E) (hF : Q.ExtensionClosure F)
    (f : E ⟶ F) : f = 0 := by
  induction hE generalizing F with
  | zero hZ => exact hZ.eq_of_src f 0
  | mem hP =>
    induction hF with
    | zero hZ => exact hZ.eq_of_tgt f 0
    | mem hQ => exact h _ _ hP hQ f
    | ext hT _ _ ihA ihB =>
      obtain ⟨g, rfl⟩ := Triangle.coyoneda_exact₂ _ hT f (ihB _)
      simp [ihA g]
  | ext hT _ _ ihX ihY =>
    obtain ⟨g, rfl⟩ := Triangle.yoneda_exact₂ _ hT f (ihX hF _)
    simp [ihY hF g]

/-- Extension closure is closed under isomorphisms. -/
theorem of_iso {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {P : ObjectProperty C} {X Y : C} (e : X ≅ Y)
    (h : P.ExtensionClosure X) : P.ExtensionClosure Y := by
  obtain ⟨Z, g, k, hT⟩ := distinguished_cocone_triangle e.hom
  have hZ : IsZero Z := (Triangle.isZero₃_iff_isIso₁ _ hT).mpr
    (show IsIso (Triangle.mk e.hom g k).mor₁ from e.isIso_hom)
  exact .ext hT h (.zero hZ)

/-- Walking a Postnikov tower: if every factor satisfies `Q`, the total object is in
`Q.ExtensionClosure`. This is the bridge from HN-filtration data to extension-closure
membership. -/
theorem of_postnikovTower {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    {Q : ObjectProperty C} {E : C} (P : Triangulated.PostnikovTower C E)
    (hfactors : ∀ i, Q (P.factor i)) : Q.ExtensionClosure E := by
  suffices h : ∀ k (hk : k ≤ P.n),
      Q.ExtensionClosure (P.chain.obj' k (by grind)) by
    exact .of_iso (Classical.choice P.top_iso) (h P.n le_rfl)
  intro k
  induction k with
  | zero =>
    intro _
    rw [show P.chain.obj' 0 (by grind) = P.chain.left from rfl]
    exact .zero P.base_isZero
  | succ k ih =>
    intro hk
    have hchain_k := ih (by grind)
    set T := P.triangle ⟨k, by grind⟩
    have hT := P.triangle_dist ⟨k, by grind⟩
    have e₁ := Classical.choice (P.triangle_obj₁ ⟨k, by grind⟩)
    have e₂ := Classical.choice (P.triangle_obj₂ ⟨k, by grind⟩)
    have h₁ : Q.ExtensionClosure T.obj₁ := .of_iso e₁.symm hchain_k
    have h₃ : Q.ExtensionClosure T.obj₃ := .mem (hfactors ⟨k, by grind⟩)
    exact .of_iso e₂ (.ext hT h₁ h₃)

end CategoryTheory.ObjectProperty.ExtensionClosure
