import BridgelandStability.ExtensionClosure
import VersoManual

open Verso.Genre Manual

set_option verso.docstring.allowMissing true

#doc (Manual) "ExtensionClosure" =>
%%%
htmlSplit := .never
%%%

# ExtensionClosure

The extension-closed subcategory generated by an object property $`P` (Bridgeland p.6). An object $`E` is in $`P^{\operatorname{ext}}` if it is zero, satisfies $`P`, or is the middle term of a distinguished triangle whose other two terms are in $`P^{\operatorname{ext}}`. This is the smallest extension-closed subcategory containing $`P` and zero objects.

Construction: An inductive type with three constructors: `zero` (any zero object is in the closure), `mem` (any object satisfying $`P` is in the closure), and `ext` (if $`X \to E \to Y \to X[1]` is distinguished and $`X, Y` are in the closure, then $`E` is in the closure).


{docstring CategoryTheory.ObjectProperty.ExtensionClosure}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20ExtensionClosure&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_eq\_zero

If generators are orthogonal ($`\operatorname{Hom}(P, Q) = 0`), their extension closures are orthogonal: every morphism from an object in $`P^{\operatorname{ext}}` to an object in $`Q^{\operatorname{ext}}` is zero.

Proof: Nested induction on the `ExtensionClosure` structure. The base case is the generator orthogonality hypothesis. The extension step uses the exact Hom sequences from the distinguished triangles: `coyoneda_exact2` and `yoneda_exact2` factor any morphism through the outer terms, where the inductive hypothesis forces it to zero.

{docstring CategoryTheory.ObjectProperty.ExtensionClosure.hom_eq_zero}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_eq_zero&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.hom_eq_zero%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# instIsClosedUnderIsomorphisms

The extension closure of any property is closed under isomorphisms: if $`E \in P^{\mathrm{ext}}` and $`E \cong F`, then $`F \in P^{\mathrm{ext}}`.

Construction: Provided by `ExtensionClosure.of_iso`.


{docstring CategoryTheory.ObjectProperty.ExtensionClosure.instIsClosedUnderIsomorphisms}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20instIsClosedUnderIsomorphisms&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.instIsClosedUnderIsomorphisms%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# instIsTriangulatedClosed₂

The extension closure is closed under extensions from distinguished triangles: if $`X, Y \in P^{\mathrm{ext}}` and $`X \to E \to Y \to X[1]` is a distinguished triangle, then $`E \in P^{\mathrm{ext}}`.

Construction: The instance witnesses `IsTriangulatedClosed₂` using the `ExtensionClosure.ext` constructor directly.


{docstring CategoryTheory.ObjectProperty.ExtensionClosure.instIsTriangulatedClosed₂}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20instIsTriangulatedClosed%E2%82%82&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.instIsTriangulatedClosed%E2%82%82%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# le\_of\_closed

Extension closure is a left adjoint: $`P^{\operatorname{ext}} \le Q` whenever $`Q` contains zero objects, contains $`P`, and is closed under extensions from distinguished triangles. This characterizes $`P^{\operatorname{ext}}` as the smallest such property.

Proof: Induction on the `ExtensionClosure` derivation, dispatching each constructor to the corresponding hypothesis.

{docstring CategoryTheory.ObjectProperty.ExtensionClosure.le_of_closed}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20le_of_closed&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.le_of_closed%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# mono

Extension closure is monotone: if $`P \le Q` (i.e., $`P(E) \Rightarrow Q(E)` for all $`E`), then $`P^{\operatorname{ext}} \le Q^{\operatorname{ext}}`.

Proof: Induction on the `ExtensionClosure` derivation: zero maps to zero, membership follows from $`P \le Q`, and extensions are preserved since the inductive hypotheses give membership in $`Q^{\operatorname{ext}}` for both outer terms.

{docstring CategoryTheory.ObjectProperty.ExtensionClosure.mono}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20mono&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.mono%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_iso

Extension closure is closed under isomorphisms: if $`X \cong Y` and $`X \in P^{\operatorname{ext}}`, then $`Y \in P^{\operatorname{ext}}`.

Proof: Complete the isomorphism $`e : X \xrightarrow{\sim} Y` to a distinguished triangle $`X \to Y \to Z \to X[1]`. Since $`e` is an iso, $`Z` is zero. Then $`Y` is an extension of $`X` (in the closure) by $`Z` (zero, hence in the closure).

{docstring CategoryTheory.ObjectProperty.ExtensionClosure.of_iso}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_iso&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.of_iso%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_postnikovTower

Walking a Postnikov tower: if every factor of a Postnikov tower of $`E` satisfies $`Q`, then $`E \in Q^{\operatorname{ext}}`. This is the bridge from HN-filtration data to extension-closure membership.

Proof: Induction on the chain length $`k`. The base case $`k = 0` uses the zero base. The inductive step uses the $`k`-th distinguished triangle: $`A_k` is in the closure by the inductive hypothesis, $`F_k` is in the closure by the factor hypothesis, and $`A_{k+1}` is an extension of the two. The top isomorphism $`A_n \cong E` transfers membership.

{docstring CategoryTheory.ObjectProperty.ExtensionClosure.of_postnikovTower}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_postnikovTower&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.ObjectProperty.ExtensionClosure.of_postnikovTower%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.ExtensionClosure%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)
