import BridgelandStability.HeartEquivalence.Basic
import VersoManual

open Verso.Genre Manual

set_option verso.docstring.allowMissing true

#doc (Manual) "HeartEquivalence: Basic" =>
%%%
htmlSplit := .never
%%%

# HeartK0

The Grothendieck group $`K_0(\operatorname{heart}(t))` of the heart of a bounded $`t`-structure, presented by short exact sequence relations.

Construction: Defined as the quotient of the free abelian group on heart objects by the subgroup generated by $`[B] - [A] - [C]` for every short exact sequence $`0 \to A \to B \to C \to 0` in the heart.


{docstring CategoryTheory.Triangulated.HeartK0}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20HeartK0&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartPresentation\_of

The $`\texttt{K0Presentation.of}` map agrees with $`\texttt{HeartK0.of}`.

Proof: Immediate by definition.

{docstring CategoryTheory.Triangulated.HeartK0.heartPresentation_of}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartPresentation_of&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.heartPresentation_of%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_ext

Two group homomorphisms from $`K_0(\operatorname{heart})` that agree on all object classes $`[E]` are equal.

Proof: Since object classes generate, the universal property of the quotient forces equality.

{docstring CategoryTheory.Triangulated.HeartK0.hom_ext}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_ext&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.hom_ext%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# hom\_ext\_iff

Two group homomorphisms from $`K_0(\operatorname{heart})` are equal if and only if they agree on all object classes.

Proof: Follows from the extensionality criterion $`\texttt{hom\_ext}` by splitting the biconditional.

{docstring CategoryTheory.Triangulated.HeartK0.hom_ext_iff}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20hom_ext_iff&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.hom_ext_iff%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# instAddCommGroup

The Grothendieck group of the heart carries a natural abelian group structure.

Proof: Inherited from the quotient construction in $`\texttt{K0Presentation.K0}`.

{docstring CategoryTheory.Triangulated.HeartK0.instAddCommGroup}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20instAddCommGroup&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.instAddCommGroup%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of

The class $`[E] \in K_0(\operatorname{heart}(t))` of a heart object $`E`.

Construction: The image of the free-abelian-group generator $`\langle E \rangle` under the quotient map.


{docstring CategoryTheory.Triangulated.HeartK0.of}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_exact

For an exact sequence $`A \xrightarrow{f} B \xrightarrow{g} D` in the heart, $`[B] = [\operatorname{im}(f)] + [\operatorname{im}(g)]`.

Proof: Factors through two short exact sequences: $`0 \to \operatorname{im}(f) \to B \to \operatorname{im}(g) \to 0` (using exactness and the first isomorphism theorem) and then applies $`\texttt{of\_shortExact}`.

{docstring CategoryTheory.Triangulated.HeartK0.of_exact}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_exact&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_exact%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_exact\_five

For a five-term exact sequence $`A_0 \to A_1 \to A_2 \to A_3 \to A_4` in the heart, $`[A_1] - [A_2] + [A_3] = [\operatorname{im}(f_0)] + [\operatorname{im}(f_3)]`.

Proof: Applies $`\texttt{of\_exact}` to each consecutive pair and uses the abelian group relation to telescope.

{docstring CategoryTheory.Triangulated.HeartK0.of_exact_five}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_exact_five&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_exact_five%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_image\_eq\_zero

The $`K_0`-class of the image of a zero morphism vanishes.

Proof: The image of the zero map is isomorphic to the zero object, so $`[\operatorname{im}(0)] = [0] = 0` by $`\texttt{of\_iso}` and $`\texttt{of\_zero}`.

{docstring CategoryTheory.Triangulated.HeartK0.of_image_eq_zero}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_image_eq_zero&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_image_eq_zero%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_isZero

The class of a zero object in the heart vanishes: $`[0] = 0` in $`K_0(\operatorname{heart})`.

Proof: Constructs a degenerate short exact sequence $`0 \to 0 \to E \to 0` and applies the defining relation.

{docstring CategoryTheory.Triangulated.HeartK0.of_isZero}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_isZero&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_isZero%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_iso

Isomorphic heart objects have equal classes in $`K_0(\operatorname{heart})`.

Proof: Constructs a short exact sequence from the isomorphism with trivial cokernel, then reads off the relation.

{docstring CategoryTheory.Triangulated.HeartK0.of_iso}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_iso&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_iso%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_shortExact

A short exact sequence $`0 \to A \to B \to C \to 0` in the heart gives $`[B] = [A] + [C]` in $`K_0(\operatorname{heart})`.

Proof: This is the defining relation of the Grothendieck group presentation.

{docstring CategoryTheory.Triangulated.HeartK0.of_shortExact}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_shortExact&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_shortExact%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_zero

The class of the explicit zero object vanishes in $`K_0(\operatorname{heart})`.

Proof: Special case of $`\texttt{of\_isZero}` applied to $`\texttt{isZero\_zero}`.

{docstring CategoryTheory.Triangulated.HeartK0.of_zero}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_zero&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartK0.of_zero%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# HeartStabilityData

A heart stability datum bundles a bounded $`t`-structure on a triangulated category $`\mathcal{C}` with a stability function on its abelian heart that has the Harder--Narasimhan property. This is one side of the equivalence in Bridgeland's Proposition 5.3.

Construction: Fields: a $`t`-structure $`t`, a proof that $`t` is bounded, a stability function $`Z` on $`t.\mathrm{heart}.\mathrm{FullSubcategory}` (which is abelian via $`\texttt{heartFullSubcategoryAbelian}`), and a proof that $`Z` satisfies the HN property.


{docstring CategoryTheory.Triangulated.HeartStabilityData}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20HeartStabilityData&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# ZOnHeartK0

The heart stability function $`Z` descends to a group homomorphism $`K_0(\operatorname{heart}(t)) \to \mathbb{C}`.

Construction: Lifts $`Z_{\mathrm{obj}}` through the free abelian group, then checks that the short-exact-sequence relations map to zero by additivity of $`Z`.


{docstring CategoryTheory.Triangulated.HeartStabilityData.ZOnHeartK0}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20ZOnHeartK0&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.ZOnHeartK0%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# ZOnHeartK0\_of

$`Z_{K_0}([E]) = Z(E)` for every heart object $`E`.

Proof: Immediate from the lifting construction.

{docstring CategoryTheory.Triangulated.HeartStabilityData.ZOnHeartK0_of}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20ZOnHeartK0_of&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.ZOnHeartK0_of%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_preimage\_of\_pure

A $`t`-pure object of degree $`n` has a preimage under the canonical map $`K_0(\operatorname{heart}) \to K_0(\mathcal{C})`.

Proof: The preimage is $`(-1)^{|n|} \cdot [X[n]]` where $`X[n]` is the heart shift. The $`K_0`-shift-parity formula verifies the identity.

{docstring CategoryTheory.Triangulated.HeartStabilityData.exists_preimage_of_pure}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_preimage_of_pure&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.exists_preimage_of_pure%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# exists\_preimage\_of\_width

Every object of bounded amplitude $`[b, b+n]` has a preimage in $`K_0(\operatorname{heart})` under the canonical map.

Proof: Induction on the width $`n`: the base case is a pure object, the inductive step splits via the truncation triangle $`\tau^{<b+n+1} E \to E \to \tau^{\ge b+n+1} E` and assembles the two preimages.

{docstring CategoryTheory.Triangulated.HeartStabilityData.exists_preimage_of_width}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20exists_preimage_of_width&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.exists_preimage_of_width%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartK0ToK0

The canonical group homomorphism $`K_0(\operatorname{heart}(t)) \to K_0(\mathcal{C})` sending $`[E]` to the class of its underlying object.

Construction: Lifts the function $`E \mapsto [E_{\mathrm{obj}}]` through the quotient, using the fact that short exact sequences in the heart lift to distinguished triangles and thus satisfy the ambient $`K_0` relation.


{docstring CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartK0ToK0&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartK0ToK0\_of

$`\operatorname{heartK0ToK0}([E]) = [E_{\mathrm{obj}}]` in $`K_0(\mathcal{C})`.

Proof: Immediate from the lifting construction.

{docstring CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0_of}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartK0ToK0_of&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0_of%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartK0ToK0\_surjective

The canonical map $`K_0(\operatorname{heart}(t)) \to K_0(\mathcal{C})` is surjective for a bounded $`t`-structure.

Proof: Every generator $`[E]` of $`K_0(\mathcal{C})` has a preimage by $`\texttt{exists\_preimage\_of\_width}` applied to the bounded amplitude of $`E`. The result extends to the full quotient by the universal property.

{docstring CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0_surjective}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartK0ToK0_surjective&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.heartK0ToK0_surjective%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartShiftOfPure

If $`X` is concentrated in $`t`-degree $`n` (i.e.\ $`X \in \mathcal{C}^{\le n} \cap \mathcal{C}^{\ge n}`), then $`X[n]` lies in the heart.

Construction: Returns $`\langle X[n], \text{proof} \rangle` where the proof that $`X[n] \in \operatorname{heart}(t)` follows from shifting the amplitude bounds by $`n`.


{docstring CategoryTheory.Triangulated.HeartStabilityData.heartShiftOfPure}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartShiftOfPure&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.heartShiftOfPure%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartZObj

The object-level central charge $`Z(E)` for a heart object $`E`, viewed as a plain function $`\operatorname{heart}(t) \to \mathbb{C}`.

Construction: Unwraps the $`\texttt{StabilityFunction.Zobj}` field from the heart stability datum, making the abelian instance explicit.


{docstring CategoryTheory.Triangulated.HeartStabilityData.heartZObj}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartZObj&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.heartZObj%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# instHeartFullSubcategoryAbelian

The heart of the $`t`-structure in a heart stability datum is an abelian category.

Proof: Delegates to the general result $`\texttt{heartFullSubcategoryAbelian}` applied to the $`t`-structure field.

{docstring CategoryTheory.Triangulated.HeartStabilityData.instHeartFullSubcategoryAbelian}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20instHeartFullSubcategoryAbelian&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.HeartStabilityData.instHeartFullSubcategoryAbelian%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_shift\_int

Shifting by $`n \in \mathbb{Z}` multiplies the Grothendieck-group class by the parity sign: $`[X[n]] = (-1)^{|n|} \cdot [X]` in $`K_0(\mathcal{C})`.

Proof: By induction on $`n` (natural and negative separately), each step uses $`[X[1]] = -[X]` from the distinguished triangle $`X \to 0 \to X[1]`.

{docstring CategoryTheory.Triangulated.K₀.of_shift_int}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_shift_int&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.K%E2%82%80.of_shift_int%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_shift\_nat

Shifting by a natural number $`n` multiplies the Grothendieck-group class by $`(-1)^n`: $`[X[n]] = (-1)^n [X]`.

Proof: Induction on $`n`: the base case is the shift-by-zero identity, and the inductive step uses $`[X[1]] = -[X]`.

{docstring CategoryTheory.Triangulated.K₀.of_shift_nat}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_shift_nat&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.K%E2%82%80.of_shift_nat%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# of\_shift\_negSucc

Shifting by $`-(n+1)` multiplies the Grothendieck-group class by $`(-1)^{n+1}`: $`[X[-(n+1)]] = (-1)^{n+1}[X]`.

Proof: Induction on $`n`: uses $`[X[-1]] = -[X]` and the inductive step for the negative direction.

{docstring CategoryTheory.Triangulated.K₀.of_shift_negSucc}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20of_shift_negSucc&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.K%E2%82%80.of_shift_negSucc%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# isZero\_of\_obj\_isZero

If the underlying object of a full-subcategory element is zero in the ambient category, then the full-subcategory element itself is zero.

Proof: Constructs the unique isomorphism from the given object to the zero object of the full subcategory, using the ambient zero-object isomorphism and the lifting property of full subcategories.

{docstring CategoryTheory.Triangulated.ObjectProperty.FullSubcategory.isZero_of_obj_isZero}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20isZero_of_obj_isZero&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.ObjectProperty.FullSubcategory.isZero_of_obj_isZero%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# P\_phi\_shortExact\_triangle

A short exact sequence $`0 \to A \to B \to Q \to 0` in the abelian slice $`\mathcal{P}(\varphi)` of a stability condition lifts to a distinguished triangle $`A \to B \to Q \to A[1]` in the ambient triangulated category $`\mathcal{C}`.

Proof: Uses the admissibility of $`\mathcal{P}(\varphi)` as an abelian subcategory together with the Hom-vanishing property to produce the octahedral lift, then verifies that the kernel--cokernel pair in the subcategory matches the triangle's first two morphisms.

{docstring CategoryTheory.Triangulated.StabilityCondition.P_phi_shortExact_triangle}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20P_phi_shortExact_triangle&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.P_phi_shortExact_triangle%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# phase\_eq\_of\_mem\_P\_phi

For $`E \in \mathcal{P}(\varphi)` nonzero and $`\varphi \in (0,1]`, the stability-function phase of $`E` on the slice equals $`\varphi`.

Proof: The compatibility axiom gives $`Z(E) = m \, e^{i\pi\varphi}` with $`m > 0`. The argument of this complex number is $`\pi\varphi`, so dividing by $`\pi` recovers $`\varphi` exactly.

{docstring CategoryTheory.Triangulated.StabilityCondition.phase_eq_of_mem_P_phi}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20phase_eq_of_mem_P_phi&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.phase_eq_of_mem_P_phi%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# stabilityFunctionOnPhase

The central charge $`Z` of a Bridgeland stability condition, restricted to $`\sigma`-semistable objects of phase $`\varphi \in (0,1]`, defines a stability function on the abelian category $`\mathcal{P}(\varphi)`.

Construction: The $`Z_{\mathrm{obj}}` field sends $`E \in \mathcal{P}(\varphi)` to $`\sigma.Z([E])` via the inclusion $`\mathcal{P}(\varphi) \hookrightarrow \mathcal{C}`. Additivity comes from $`K_0`-additivity on short exact sequences lifted through $`\texttt{P\_phi\_shortExact\_triangle}`. The upper half-plane condition uses the compatibility axiom $`Z(E) = m \cdot e^{i\pi\varphi}` with $`m > 0`.


{docstring CategoryTheory.Triangulated.StabilityCondition.stabilityFunctionOnPhase}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20stabilityFunctionOnPhase&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.stabilityFunctionOnPhase%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# stabilityFunctionOnPhase\_hasHN

For $`\varphi \in (0,1]`, every nonzero object of $`\mathcal{P}(\varphi)` admits a Harder--Narasimhan filtration with respect to the restricted stability function.

Proof: Every nonzero object of $`\mathcal{P}(\varphi)` is already semistable of phase $`\varphi`, so the HN filtration is trivial (a single factor). Existence of semistable filtrations then follows from the general abelian-category HN existence theorem.

{docstring CategoryTheory.Triangulated.StabilityCondition.stabilityFunctionOnPhase_hasHN}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20stabilityFunctionOnPhase_hasHN&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.StabilityCondition.stabilityFunctionOnPhase_hasHN%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartFullSubcategory\_shortExact\_of\_distTriang

A distinguished triangle whose three vertices lie in the heart induces a short exact sequence in the heart abelian category.

Proof: Applies the kernel and cokernel fork constructions from the triangulated-abelian-subcategory API to the given triangle, verifying monicity of the first map and epicity of the second.

{docstring CategoryTheory.Triangulated.TStructure.heartFullSubcategory_shortExact_of_distTriang}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartFullSubcategory_shortExact_of_distTriang&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.TStructure.heartFullSubcategory_shortExact_of_distTriang%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartFullSubcategory\_shortExact\_triangle

A short exact sequence $`0 \to A \to B \to Q \to 0` in the heart of a $`t`-structure lifts to a distinguished triangle $`A \to B \to Q \to A[1]` in the ambient triangulated category.

Proof: Uses the admissibility of the heart as a full abelian subcategory: a short exact sequence yields a cofiber sequence via the triangulated-abelian-subcategory machinery, then the kernel--cokernel pair is identified with the given mono--epi pair by uniqueness.

{docstring CategoryTheory.Triangulated.TStructure.heartFullSubcategory_shortExact_triangle}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartFullSubcategory_shortExact_triangle&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.TStructure.heartFullSubcategory_shortExact_triangle%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)

# heartPresentation

The $`K_0`-presentation for the heart of a bounded $`t`-structure: generators are heart objects and relations are short exact sequences in the heart.

Construction: An abbreviation packaging the three projection functions $`\mathrm{obj}_1, \mathrm{obj}_2, \mathrm{obj}_3` from the set of short exact short complexes in the heart into the $`\texttt{K0Presentation}` API.


{docstring CategoryTheory.Triangulated.heartPresentation}

Something wrong, better idea? [Suggest a change](https://github.com/mattrobball/BridgelandStability/issues/new?title=Review%3A%20heartPresentation&body=%2A%2ADeclaration%3A%2A%2A%20%60CategoryTheory.Triangulated.heartPresentation%60%0A%2A%2AModule%3A%2A%2A%20%60BridgelandStability.HeartEquivalence.Basic%60%0A%2A%2ASource%3A%2A%2A%20unavailable%0A---%0A%2A%2ADescribe%20the%20issue%3A%2A%2A&labels=exposition-review)
